SUBDIR1 = ./crawler_schduler
SUBDIR2 = ./manager
SUBDIR3 = ./robot_task
MAKE = make
CLEAN = make clean
subsystem:
	cd $(SUBDIR1)&&$(CLEAN)&&$(MAKE)
	cd $(SUBDIR2)&&$(CLEAN)&&$(MAKE)
	cd $(SUBDIR3)&&$(CLEAN)&&$(MAKE)
