SUBDIR1 = ./crawler_schduler
SUBDIR2 = ./crawler_task
SUBDIR3 = ./manager
SUBDIR4 = ./qzone_task
SUBDIR5 = ./tianya_task
SUBDIR6 = ./weibo_task
SUBDIR7 = ./tieba_task
MAKE = make
CLEAN = make clean
subsystem:
	cd $(SUBDIR1)&&$(CLEAN)&&$(MAKE)
	#cd $(SUBDIR2)&&$(CLEAN)&&$(MAKE)
	cd $(SUBDIR3)&&$(CLEAN)&&$(MAKE)
	#cd $(SUBDIR4)&&$(CLEAN)&&$(MAKE)
	#cd $(SUBDIR5)&&$(CLEAN)&&$(MAKE)
	#cd $(SUBDIR6)&&$(CLEAN)&&$(MAKE)
	cd $(SUBDIR7)&&$(CLEAN)&&$(MAKE)
